login:
    pattern:   /login
    defaults:  { _controller: SimpleProfileBundle:Security:login }

login_check:
    pattern:   /login_check

test_security:
    pattern: /secure_area
    defaults: { _controller: SimpleProfileBundle:Security:dumpString }