parameters:
#    simple_profile.example.class: Simple\ProfileBundle\Example

services:
#    simple_profile.example:
#        class: %simple_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
