acme_task_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeTaskBundle:Default:index }

acme_task_new:
    path:    /new 
    defaults: { _controller: AcmeTaskBundle:Default:new }